[package]
name = "playing-around-with-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.40"
futures-util = "0.3.31"
rand = "0.9.0"
tokio = { version = "1.44.1", features = ["full"] }
tokio-tungstenite = "0.26.2"
uuid = "1.16.0"
warp = "0.3.7"
