services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    restart: always
    ports:
      - "16686:16686"  # UI do Jaeger
      - "14268:14268"  # API HTTP para enviar traces
      - "14250:14250"  # API gRPC para coletar traces
      - "6831:6831/udp" # Protocolo UDP para OpenTelemetry
      - "5778:5778"     # API de configuração remota
      - "4317:4317"     # Endpoint OTLP gRPC para OpenTelemetry
      - "4318:4318"     # Endpoint OTLP HTTP para OpenTelemetry
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
      - LOG_LEVEL=debug
      - METRICS_STORAGE_TYPE=prometheus
      - PROMETHEUS_SERVER=http://prometheus:9090

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  grafana-storage:
